services:
  redis: 
    image: redis:latest
    container_name: redis
  django: 
    container_name: django
    build: 
      context: ./dcelery
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./dcelery:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=secret
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis
  celery:
    container_name: celery
    build: 
      context: ./dcelery
    command: celery --app=dcelery worker --loglevel=info
    volumes:
      - ./dcelery:/usr/src/app/
    ports:
      - 8001:8001
    environment:
      - DEBUG=1
      - SECRET_KEY=secret
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis